version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@pcrnj9gfyxoo5cfh_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=FS9_MS_BD
      - spring.datasource.password=ExamenTransversal123
    restart: always